import 'dotenv/config';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

import User from '../models/User';
import Category from '../models/Category';
import Collection from '../models/Collection';
import ProductType from '../models/ProductType';
import Attribute from '../models/Attribute';
import Product from '../models/Product';
import SizeChart from '../models/SizeChart';
import Coupon from '../models/Coupon';
import Announcement from '../models/Announcement';
import Blog from '../models/Blog';
import Review from '../models/Review';
import Newsletter from '../models/Newsletter';
import CmsPage from '../models/CmsPage';
import AuditLog from '../models/AuditLog';
import Order from '../models/Order';
import Provider from '../models/Provider';

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/styleinneed_fashions';

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Variant helpers
const makeV = (prefix: string, colors: string[], sizes: string[]) =>
  colors.flatMap((c, ci) =>
    sizes.map((s, si) => ({
      sku: `${prefix}-${c.slice(0, 3).toUpperCase()}-${s.replace(/\s+/g, '')}`,
      stock: Math.max(8, 20 - ci * 2 - si),
      attributes: { color: c, size: s },
    }))
  );

const freeV = (prefix: string, colors: string[]) =>
  colors.map((c, ci) => ({
    sku: `${prefix}-${c.slice(0, 3).toUpperCase()}-FS`,
    stock: Math.max(8, 18 - ci * 2),
    attributes: { color: c, size: 'Free Size' },
  }));

const banV = (prefix: string, color: string) => [
  { sku: `${prefix}-S`, stock: 22, attributes: { color, size: 'S' } },
  { sku: `${prefix}-M`, stock: 26, attributes: { color, size: 'M' } },
  { sku: `${prefix}-L`, stock: 18, attributes: { color, size: 'L' } },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB');

  await Promise.all([
    User.deleteMany({}),
    Category.deleteMany({}),
    Collection.deleteMany({}),
    ProductType.deleteMany({}),
    Attribute.deleteMany({}),
    Product.deleteMany({}),
    SizeChart.deleteMany({}),
    Coupon.deleteMany({}),
    Announcement.deleteMany({}),
    Blog.deleteMany({}),
    Review.deleteMany({}),
    Newsletter.deleteMany({}),
    CmsPage.deleteMany({}),
    AuditLog.deleteMany({}),
    Order.deleteMany({}),
    Provider.deleteMany({}),
  ]);
  console.log('Cleared all collections');

  const passwordHash = await bcrypt.hash('Admin@123', 12);
  const customerHash = await bcrypt.hash('Customer@123', 12);

  const [admin] = await User.insertMany([
    { name: 'Admin', email: 'admin@styleinneed.com', password: passwordHash, role: 'admin', isEmailVerified: true, isActive: true, phone: '9876543210' },
    { name: 'Priya Sharma', email: 'priya@example.com', password: customerHash, role: 'customer', isEmailVerified: true, isActive: true, phone: '9876500001' },
    { name: 'Anitha Reddy', email: 'anitha@example.com', password: customerHash, role: 'customer', isEmailVerified: true, isActive: true, phone: '9876500002' },
  ]);
  console.log('Users created');

  const catData = [
    { name: 'Sarees', productType: 'clothing', description: 'Premium Indian sarees from across the country', sortOrder: 1 },
    { name: 'Silk Sarees', productType: 'clothing', description: 'Handwoven silk sarees in Kanjeevaram, Banarasi and more', sortOrder: 2 },
    { name: 'Cotton Sarees', productType: 'clothing', description: 'Lightweight and breathable cotton sarees', sortOrder: 3 },
    { name: 'Designer Sarees', productType: 'clothing', description: 'Contemporary designer sarees for special occasions', sortOrder: 4 },
    { name: 'Kurtis', productType: 'clothing', description: 'Versatile kurtis for every occasion', sortOrder: 5 },
    { name: 'Kurta Sets', productType: 'clothing', description: 'Matching kurta and bottom sets', sortOrder: 6 },
    { name: 'Lehengas', productType: 'clothing', description: 'Bridal and festive lehengas', sortOrder: 7 },
    { name: 'Salwar Suits', productType: 'clothing', description: 'Classic and contemporary salwar suits', sortOrder: 8 },
    { name: 'Tops', productType: 'clothing', description: 'Trendy tops for casual and formal wear', sortOrder: 9 },
    { name: 'Dresses', productType: 'clothing', description: 'Western dresses for all occasions', sortOrder: 10 },
    { name: 'Jeans & Trousers', productType: 'clothing', description: 'Modern western bottoms', sortOrder: 11 },
    { name: 'Co-Ord Sets', productType: 'clothing', description: 'Matching top and bottom co-ordinate sets', sortOrder: 12 },
    { name: 'Necklaces', productType: 'jewellery', description: '1 gram gold, rolled gold and silver necklaces', sortOrder: 13 },
    { name: 'Earrings', productType: 'jewellery', description: 'Studs, jhumkas and danglers', sortOrder: 14 },
    { name: 'Bangles', productType: 'jewellery', description: 'Traditional and contemporary bangles', sortOrder: 15 },
    { name: 'Return Gifts', productType: 'return-gift', description: 'Indian return gift items for functions', sortOrder: 16 },
  ];
  const categories = await Category.insertMany(catData.map((c) => ({ ...c, slug: slug(c.name), isActive: true })));
  console.log('Categories created');

  const collData = [
    { name: 'Wedding Collection', description: 'Exquisite pieces for your wedding and special occasions', isFeatured: true, sortOrder: 1 },
    { name: 'Festive Collection', description: 'Celebrate every festival in style', isFeatured: true, sortOrder: 2 },
    { name: 'New Arrivals', description: 'Fresh additions to our catalogue', isFeatured: true, sortOrder: 3 },
    { name: 'Summer Essentials', description: 'Light, breezy and stylish summer picks', isFeatured: false, sortOrder: 4 },
    { name: 'Diwali Collection', description: 'Shimmer and shine this Diwali season', isFeatured: true, sortOrder: 5 },
    { name: 'Office Wear', description: 'Professional and elegant office attire', isFeatured: false, sortOrder: 6 },
    { name: 'Bridal Trousseau', description: 'Complete bridal wardrobe essentials', isFeatured: true, sortOrder: 7 },
  ];
  const collections = await Collection.insertMany(collData.map((c) => ({ ...c, slug: slug(c.name), isActive: true })));
  console.log('Collections created');

  await ProductType.insertMany(
    [
      { name: 'Clothing', sortOrder: 1 },
      { name: 'Jewellery', sortOrder: 2 },
      { name: 'Return Gift', sortOrder: 3 },
      { name: 'Accessory', sortOrder: 4 },
    ].map((t) => ({ ...t, slug: slug(t.name), isActive: true }))
  );
  console.log('Product types created');

  const opt = (vals: string[]) => vals.map((v, i) => ({ label: v, value: v, sortOrder: i }));
  const colorOpt = (pairs: [string, string][]) =>
    pairs.map(([label, hex], i) => ({ label, value: label, hex, sortOrder: i }));
  await Attribute.insertMany([
    { name: 'Size', slug: 'size', level: 'variant', inputType: 'chips', isFilterable: true, isActive: true, productTypes: ['clothing'], sortOrder: 1, options: opt(['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Free Size']) },
    { name: 'Colour', slug: 'color', level: 'variant', inputType: 'color', isFilterable: true, isActive: true, productTypes: [], sortOrder: 2, options: colorOpt([['Red', '#EF4444'], ['Blue', '#3B82F6'], ['Green', '#22C55E'], ['Pink', '#EC4899'], ['Black', '#111827'], ['White', '#F9FAFB'], ['Gold', '#C8A97E'], ['Beige', '#D4A57C']]) },
    { name: 'Fabric', slug: 'fabric', level: 'product', inputType: 'chips', isFilterable: true, isActive: true, productTypes: ['clothing'], sortOrder: 3, options: opt(['Silk', 'Cotton', 'Georgette', 'Chiffon', 'Linen', 'Velvet', 'Net', 'Crepe', 'Satin']) },
    { name: 'Metal', slug: 'metal', level: 'product', inputType: 'select', isFilterable: true, isActive: true, productTypes: ['jewellery', 'return-gift'], sortOrder: 4, options: opt(['1 Gram Gold', 'Rolled Gold', 'Original Silver', 'Imitation']) },
    { name: 'Purity', slug: 'purity', level: 'product', inputType: 'chips', isFilterable: true, isActive: true, productTypes: ['jewellery'], sortOrder: 5, options: opt(['22K', '18K', '92.5 Silver', 'Gold Plated']) },
    { name: 'Occasion', slug: 'occasion', level: 'product', inputType: 'chips', isFilterable: true, isActive: true, productTypes: [], sortOrder: 6, options: opt(['Wedding', 'Festive', 'Daily Wear', 'Party', 'Return Gift', 'Bridal']) },
  ]);
  console.log('Attributes created');

  const now = new Date();
  const futureDate = new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000);
  const nearFuture = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

  await Coupon.insertMany([
    { code: 'WELCOME10', type: 'percentage', value: 10, minOrderValue: 999, maxDiscount: 500, usageLimit: 1000, perUserLimit: 1, startDate: now, expiryDate: futureDate, isActive: true, description: '10% off on your first order' },
    { code: 'FLAT500', type: 'flat', value: 500, minOrderValue: 2999, usageLimit: 500, perUserLimit: 2, startDate: now, expiryDate: futureDate, isActive: true, description: 'Flat ₹500 off on orders above ₹2999' },
    { code: 'FREESHIP', type: 'free_shipping', value: 0, minOrderValue: 499, usageLimit: 2000, perUserLimit: 5, startDate: now, expiryDate: futureDate, isActive: true, description: 'Free shipping on all orders above ₹499' },
    { code: 'DIWALI15', type: 'festival', value: 15, minOrderValue: 1999, maxDiscount: 1500, usageLimit: 1000, perUserLimit: 2, startDate: now, expiryDate: nearFuture, isActive: true, description: 'Diwali special — 15% off' },
  ]);
  console.log('Coupons created');

  await Announcement.insertMany([
    { title: 'Free Shipping', content: '🎉 Free Shipping on orders above ₹999 | Use code FREESHIP', type: 'top_bar', startDate: now, expiryDate: futureDate, isActive: true, bgColor: '#C8A97E', textColor: '#FFFFFF', ctaText: 'Shop Now', ctaLink: '/products' },
    { title: 'Welcome Popup', content: 'Welcome to Style In Need Fashions! Get 10% off your first order with code WELCOME10', type: 'popup', ctaText: 'Shop Now', ctaLink: '/products', startDate: now, expiryDate: futureDate, isActive: true, bgColor: '#1C1C1C', textColor: '#FFFFFF' },
    { title: 'Diwali Sale', content: '✨ Diwali Special — Up to 25% off on ethnic wear! Limited time only', type: 'flash_sale', startDate: now, expiryDate: nearFuture, isActive: true, bgColor: '#D8A7B1', textColor: '#1C1C1C', ctaText: 'Grab Now', ctaLink: '/products?collection=diwali-collection' },
  ]);
  console.log('Announcements created');

  await Blog.insertMany([
    {
      title: 'How to Style a Kanjeevaram Saree for Modern Occasions',
      slug: 'how-to-style-kanjeevaram-saree-modern-occasions',
      excerpt: 'The Kanjeevaram saree has been a bridal staple for centuries. Here is your complete guide to styling it for contemporary settings.',
      content: `<h2>The Timeless Kanjeevaram</h2><p>The Kanjeevaram saree, woven in Kanchipuram, is one of India's most prized silk traditions.</p><h2>Modern Styling Tips</h2><ul><li><strong>Belt it up</strong></li><li><strong>The dhoti drape</strong></li><li><strong>Cape blouse</strong></li><li><strong>Minimalist jewellery</strong></li></ul>`,
      coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=80',
      author: admin._id,
      category: 'Style Guide',
      tags: ['kanjeevaram', 'saree styling', 'bridal', 'silk'],
      isPublished: true,
      publishedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'A Guide to Indian Handloom Fabrics Every Woman Should Know',
      slug: 'guide-to-indian-handloom-fabrics',
      excerpt: 'From Mysore silk to Chanderi, here is your definitive guide to the fabrics that define Indian fashion.',
      content: `<h2>India's Handloom Heritage</h2><p>India's handloom industry is the world's largest.</p><h3>Kanjeevaram Silk</h3><p>Heavy weight, rich zari borders.</p><h3>Banarasi Silk</h3><p>Intricate brocade with gold and silver thread.</p><h3>Chanderi</h3><p>Lightweight silk-cotton blend.</p>`,
      coverImage: 'https://images.unsplash.com/photo-1614093302611-8efc4c438a87?w=1200&q=80',
      author: admin._id,
      category: 'Fashion Education',
      tags: ['handloom', 'indian textiles', 'silk', 'fabric guide'],
      isPublished: true,
      publishedAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000),
    },
  ]);
  console.log('Blogs created');

  await Provider.insertMany([
    { name: 'Sri Lakshmi Textiles', contactPerson: 'Ramesh Kumar', phone: '9876543001', email: 'srilakshmi@textiles.com', category: 'clothing', city: 'Kanchipuram', state: 'Tamil Nadu', gstin: '33AABCS1429B1ZX', isActive: true },
    { name: 'Hyderabad Jewellery House', contactPerson: 'Suresh Reddy', phone: '9876543002', email: 'hjhouse@jewellery.com', category: 'jewellery', city: 'Hyderabad', state: 'Telangana', gstin: '36AABCH5678C1ZX', isActive: true },
    { name: 'Style In Need Return Gifts', contactPerson: 'Pradeep Naidu', phone: '9876543003', email: 'styleinneed.gifts@gmail.com', category: 'accessories', city: 'Bengaluru', state: 'Karnataka', isActive: true },
    { name: 'Mumbai Fashion Wholesale', contactPerson: 'Amit Shah', phone: '9876543004', email: 'mfw@fashion.com', category: 'all', city: 'Mumbai', state: 'Maharashtra', isActive: true },
  ]);
  console.log('Providers created');

  await Newsletter.insertMany([
    { email: 'newsletter1@example.com', isSubscribed: true, source: 'website' },
    { email: 'newsletter2@example.com', isSubscribed: true, source: 'popup' },
    { email: 'priya@example.com', isSubscribed: true, source: 'website' },
  ]);
  console.log('Newsletter subscribers created');

  await CmsPage.insertMany([
    {
      key: 'homepage_hero',
      title: 'Homepage Hero',
      content: {
        slides: [
          { title: 'Elegance\nRedefined', subtitle: 'Discover premium ethnic and western wear', label: 'New Collection 2025', ctaLabel: 'Shop Now', ctaHref: '/products' },
          { title: 'Bridal\nSplendour', subtitle: 'Handcrafted silk sarees for your special day', label: 'Wedding Collection', ctaLabel: 'Explore', ctaHref: '/products?collection=wedding-collection' },
        ],
      },
      lastUpdatedBy: admin._id,
    },
    {
      key: 'about',
      title: 'About Us',
      content: {
        heading: 'Our Story',
        body: 'Born from a deep love for Indian textiles and craftsmanship, Style In Need Fashions bridges traditional weaves with contemporary silhouettes.',
        stats: [{ label: 'Products', value: '5000+' }, { label: 'Happy Customers', value: '50K+' }, { label: 'Years', value: '12+' }],
      },
      lastUpdatedBy: admin._id,
    },
    { key: 'privacy', title: 'Privacy Policy', content: `<h2>Privacy Policy</h2><p>We are committed to protecting your privacy.</p>`, lastUpdatedBy: admin._id },
    { key: 'terms', title: 'Terms of Service', content: `<h2>Terms of Service</h2><p>By using Style In Need Fashions, you agree to these terms.</p>`, lastUpdatedBy: admin._id },
    { key: 'returns', title: 'Return Policy', content: `<h2>Return & Refund Policy</h2><p>Hassle-free returns within 7 days of delivery.</p>`, lastUpdatedBy: admin._id },
    { key: 'shipping', title: 'Shipping Policy', content: `<h2>Shipping Policy</h2><p>Free standard shipping on all orders above ₹999.</p>`, lastUpdatedBy: admin._id },
  ]);
  console.log('CMS pages created');

  // ── Size Charts ─────────────────────────────────────────────────────────────
  const sizeChartDocs = await SizeChart.insertMany([
    {
      name: 'Kurtis & Tops Standard',
      productTypes: ['kurtis', 'clothing'],
      columns: ['Bust (cm)', 'Waist (cm)', 'Hip (cm)', 'Length (cm)'],
      unit: 'cm',
      isActive: true,
      rows: [
        { size: 'XS', values: ['76', '60', '82', '38'] },
        { size: 'S',  values: ['80', '64', '86', '40'] },
        { size: 'M',  values: ['84', '68', '90', '42'] },
        { size: 'L',  values: ['88', '72', '94', '44'] },
        { size: 'XL', values: ['92', '76', '98', '46'] },
        { size: 'XXL',values: ['96', '80', '102','48'] },
      ],
    },
    {
      name: 'Lehenga & Skirts Standard',
      productTypes: ['lehengas', 'clothing'],
      columns: ['Waist (cm)', 'Hip (cm)', 'Skirt Length (cm)'],
      unit: 'cm',
      isActive: true,
      rows: [
        { size: 'XS', values: ['60', '82', '40'] },
        { size: 'S',  values: ['64', '86', '42'] },
        { size: 'M',  values: ['68', '90', '44'] },
        { size: 'L',  values: ['72', '94', '46'] },
        { size: 'XL', values: ['76', '98', '48'] },
      ],
    },
    {
      name: 'Pants & Trousers Standard',
      productTypes: ['pants', 'clothing'],
      columns: ['Waist (cm)', 'Hip (cm)', 'Inseam (cm)'],
      unit: 'cm',
      isActive: true,
      rows: [
        { size: 'XS', values: ['60', '82', '74'] },
        { size: 'S',  values: ['64', '86', '75'] },
        { size: 'M',  values: ['68', '90', '76'] },
        { size: 'L',  values: ['72', '94', '77'] },
        { size: 'XL', values: ['76', '98', '78'] },
      ],
    },
    {
      name: 'Sarees — Free Size Guide',
      productTypes: ['sarees', 'clothing'],
      columns: ['Saree Length (m)', 'Blouse Piece (m)'],
      unit: 'cm',
      isActive: true,
      rows: [
        { size: 'Free Size', values: ['5.5', '0.8'] },
      ],
    },
    {
      name: 'Bangles & Jewellery Wrist Guide',
      productTypes: ['jewelry', 'jewellery'],
      columns: ['Wrist Circumference (cm)', 'Inner Diameter (cm)'],
      unit: 'cm',
      isActive: true,
      rows: [
        { size: 'S', values: ['14–15', '5.4'] },
        { size: 'M', values: ['15–16', '5.8'] },
        { size: 'L', values: ['16–17', '6.2'] },
      ],
    },
  ]);
  const [kurtisChart, lehenasChart, pantsChart, sareeChart, banglesChart] = sizeChartDocs;
  console.log('Size charts created');

  // ── Products ──────────────────────────────────────────────────────────────
  const disc = (mrp: number, sale: number) => mrp > 0 ? Math.round(((mrp - sale) / mrp) * 100) : 0;

  const [
    sarCat, silkSarCat, cottonSarCat, designerSarCat,
    kurtiCat, kurtaSetCat, lehengaCat, salwarCat,
    topCat, dressCat, jeansCat, coordCat,
    necklaceCat, earringCat, bangleCat, returnGiftCat,
  ] = categories;

  const [weddingCol, festiveCol, newArrivalsCol, summerCol, diwaliCol, officeCol, bridalCol] = collections;

  const IMG = {
    saree1: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80',
    saree2: 'https://images.unsplash.com/photo-1614093302611-8efc4c438a87?w=800&q=80',
    saree3: 'https://images.unsplash.com/photo-1583391099993-0d8f2c4a0a6d?w=800&q=80',
    ethnic1: 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80',
    ethnic2: 'https://images.unsplash.com/photo-1583391099995-7bde459882b2?w=800&q=80',
    lehenga1: 'https://images.unsplash.com/photo-1617627143233-bc4630f7e58b?w=800&q=80',
    western1: 'https://images.unsplash.com/photo-1551232864-3f5ade02b2e4?w=800&q=80',
    western2: 'https://images.unsplash.com/photo-1521577352947-9bb58764b69a?w=800&q=80',
    western3: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80',
    jewel1: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80',
    jewel2: 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=800&q=80',
    jewel3: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80',
    gift1: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80',
  };

  const products = await Product.insertMany([

    // ─── SAREES (Free Size × multiple colors) ─────────────────────────────
    {
      name: 'Banarasi Brocade Saree in Royal Purple',
      slug: 'banarasi-brocade-saree-royal-purple',
      description: 'Handwoven Banarasi brocade saree with intricate gold zari work. Available in multiple rich colours. Includes matching unstitched blouse piece.',
      shortDescription: 'Handwoven Banarasi brocade with gold zari work.',
      productType: 'clothing', category: sarCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Wedding', 'Festive'] },
      mrp: 8999, salePrice: 6999, discountPercentage: disc(8999, 6999),
      images: [IMG.saree1], tags: ['banarasi', 'silk', 'wedding', 'zari'],
      isFeatured: true, isBestSeller: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SAR-001', ['Red', 'Blue', 'Green', 'Pink', 'Gold']),
    },
    {
      name: 'Mysore Pure Silk Saree with Gold Border',
      slug: 'mysore-pure-silk-saree-gold-border',
      description: 'Soft and lustrous Mysore pure silk saree with a classic gold border. Available in multiple classic shades. Perfect for weddings and festive events.',
      shortDescription: 'Lustrous Mysore silk with classic gold border.',
      productType: 'clothing', category: sarCat._id,
      collections: [festiveCol._id, weddingCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Wedding', 'Festive'] },
      mrp: 12999, salePrice: 9999, discountPercentage: disc(12999, 9999),
      images: [IMG.saree2], tags: ['mysore', 'silk', 'gold border'],
      isFeatured: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SAR-002', ['Red', 'Blue', 'Pink', 'Green', 'Beige']),
    },
    {
      name: 'Handloom Tant Cotton Saree',
      slug: 'handloom-tant-cotton-saree',
      description: 'Lightweight handloom tant cotton saree from West Bengal, ideal for daily wear and casual occasions. Available in vibrant colours.',
      shortDescription: 'Lightweight Bengali tant cotton for daily wear.',
      productType: 'clothing', category: sarCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 2999, salePrice: 1999, discountPercentage: disc(2999, 1999),
      images: [IMG.saree3], tags: ['tant', 'cotton', 'handloom', 'daily'],
      isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SAR-003', ['Blue', 'Green', 'Red', 'Beige', 'White']),
    },
    {
      name: 'Chiffon Printed Party Saree',
      slug: 'chiffon-printed-party-saree',
      description: 'Flowing chiffon saree with an all-over floral digital print. Available in gorgeous party shades. Great for parties and receptions.',
      shortDescription: 'Flowy chiffon with digital floral print.',
      productType: 'clothing', category: sarCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Chiffon'], occasion: ['Party'] },
      mrp: 3499, salePrice: 2499, discountPercentage: disc(3499, 2499),
      images: [IMG.ethnic1], tags: ['chiffon', 'party', 'printed'],
      isNewArrival: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SAR-004', ['Pink', 'Red', 'Blue', 'Gold']),
    },
    {
      name: 'Chanderi Silk Cotton Saree',
      slug: 'chanderi-silk-cotton-saree',
      description: 'Elegant Chanderi silk-cotton blend saree with subtle woven motifs and sheer texture. Suitable for office and casual occasions.',
      shortDescription: 'Sheer Chanderi silk-cotton with woven motifs.',
      productType: 'clothing', category: sarCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Silk', 'Cotton'], occasion: ['Daily Wear'] },
      mrp: 4999, salePrice: 3499, discountPercentage: disc(4999, 3499),
      images: [IMG.saree2], tags: ['chanderi', 'silk cotton', 'office'],
      isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SAR-005', ['Beige', 'White', 'Pink', 'Blue']),
    },

    // ─── SILK SAREES ───────────────────────────────────────────────────────
    {
      name: 'Kanjivaram Bridal Red Silk Saree',
      slug: 'kanjivaram-bridal-red-silk-saree',
      description: 'Authentic Kanjivaram silk saree with heavy gold zari border and traditional temple motifs. Available in bridal colours.',
      shortDescription: 'Authentic Kanjivaram with heavy gold zari temple border.',
      productType: 'clothing', category: silkSarCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Wedding', 'Bridal'] },
      mrp: 18999, salePrice: 14999, discountPercentage: disc(18999, 14999),
      images: [IMG.saree1], tags: ['kanjivaram', 'bridal', 'silk', 'zari'],
      isFeatured: true, isBestSeller: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SSR-001', ['Red', 'Pink', 'Green', 'Blue']),
    },
    {
      name: 'Banarasi Gold Tissue Silk Saree',
      slug: 'banarasi-gold-tissue-silk-saree',
      description: 'Luxurious Banarasi gold tissue silk saree woven with silver and gold thread, perfect for grand wedding ceremonies.',
      shortDescription: 'Banarasi gold tissue silk with silver-gold thread weave.',
      productType: 'clothing', category: silkSarCat._id,
      collections: [weddingCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Wedding', 'Festive'] },
      mrp: 15999, salePrice: 11999, discountPercentage: disc(15999, 11999),
      images: [IMG.saree2], tags: ['banarasi', 'gold tissue', 'wedding'],
      isFeatured: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SSR-002', ['Gold', 'Red', 'Pink', 'White']),
    },
    {
      name: 'Gadwal Silk Saree with Contrast Border',
      slug: 'gadwal-silk-saree-contrast-border',
      description: 'Traditional Gadwal silk saree from Telangana featuring a distinctive contrast border and pure silk body with cotton core.',
      shortDescription: 'Traditional Gadwal silk with vibrant contrast border.',
      productType: 'clothing', category: silkSarCat._id,
      collections: [festiveCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Festive', 'Wedding'] },
      mrp: 9999, salePrice: 7499, discountPercentage: disc(9999, 7499),
      images: [IMG.ethnic1], tags: ['gadwal', 'silk', 'telangana'],
      isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SSR-003', ['Green', 'Red', 'Blue', 'Pink']),
    },
    {
      name: 'Pochampally Ikat Silk Saree',
      slug: 'pochampally-ikat-silk-saree',
      description: 'GI-tagged Pochampally ikat silk saree with bold geometric patterns created using the traditional tie-dye weaving technique.',
      shortDescription: 'GI-tagged Pochampally ikat with bold geometric patterns.',
      productType: 'clothing', category: silkSarCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Festive', 'Daily Wear'] },
      mrp: 7999, salePrice: 5999, discountPercentage: disc(7999, 5999),
      images: [IMG.saree3], tags: ['pochampally', 'ikat', 'geometric'],
      isTrending: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SSR-004', ['Blue', 'Red', 'Green', 'Beige']),
    },
    {
      name: 'Dharmavaram Pure Silk Saree',
      slug: 'dharmavaram-pure-silk-saree',
      description: 'Heavy Dharmavaram pure silk saree from Andhra Pradesh known for its bright colours and wide, ornate zari borders.',
      shortDescription: 'Heavy Dharmavaram silk with ornate wide zari border.',
      productType: 'clothing', category: silkSarCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Wedding', 'Bridal', 'Festive'] },
      mrp: 13999, salePrice: 10999, discountPercentage: disc(13999, 10999),
      images: [IMG.saree1], tags: ['dharmavaram', 'silk', 'andhra'],
      isBestSeller: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('SSR-005', ['Pink', 'Red', 'Green', 'Gold', 'Blue']),
    },

    // ─── COTTON SAREES ─────────────────────────────────────────────────────
    {
      name: 'Bengal Tant Cotton Saree in Indigo',
      slug: 'bengal-tant-cotton-saree-indigo',
      description: 'Crisp and breezy Bengal tant cotton saree with woven stripe pattern and thin zari border, ideal for summer daily wear.',
      shortDescription: 'Crisp Bengali tant with woven stripes for daily wear.',
      productType: 'clothing', category: cottonSarCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1299, salePrice: 899, discountPercentage: disc(1299, 899),
      images: [IMG.saree3], tags: ['tant', 'cotton', 'bengal', 'summer'],
      isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('CSR-001', ['Blue', 'Green', 'White', 'Beige', 'Red']),
    },
    {
      name: 'Kalamkari Block Print Cotton Saree',
      slug: 'kalamkari-block-print-cotton-saree',
      description: 'Handcrafted Kalamkari cotton saree with natural dye block prints depicting traditional motifs from Andhra Pradesh.',
      shortDescription: 'Natural dye Kalamkari block print cotton saree.',
      productType: 'clothing', category: cottonSarCat._id,
      collections: [festiveCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Festive', 'Daily Wear'] },
      mrp: 1999, salePrice: 1499, discountPercentage: disc(1999, 1499),
      images: [IMG.ethnic1], tags: ['kalamkari', 'block print', 'natural dye'],
      isTrending: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('CSR-002', ['Beige', 'Red', 'Green', 'Blue']),
    },
    {
      name: 'Khadi Woven Cotton Saree',
      slug: 'khadi-woven-cotton-saree',
      description: 'Handspun khadi cotton saree with a textured weave and minimalist design. Sustainable, eco-friendly, and comfortable.',
      shortDescription: 'Handspun khadi cotton — sustainable and comfortable.',
      productType: 'clothing', category: cottonSarCat._id,
      collections: [officeCol._id, summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 2499, salePrice: 1799, discountPercentage: disc(2499, 1799),
      images: [IMG.saree2], tags: ['khadi', 'sustainable', 'handspun'],
      isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('CSR-003', ['White', 'Beige', 'Blue', 'Green']),
    },
    {
      name: 'Jamdani Fine Cotton Saree',
      slug: 'jamdani-fine-cotton-saree',
      description: 'UNESCO-recognised Jamdani muslin cotton saree with intricate supplementary weft floral motifs. Lightweight and heirloom-quality.',
      shortDescription: 'UNESCO Jamdani muslin with intricate weft floral motifs.',
      productType: 'clothing', category: cottonSarCat._id,
      collections: [festiveCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Festive', 'Wedding'] },
      mrp: 3499, salePrice: 2499, discountPercentage: disc(3499, 2499),
      images: [IMG.saree3], tags: ['jamdani', 'muslin', 'floral'],
      isFeatured: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('CSR-004', ['White', 'Beige', 'Pink', 'Blue']),
    },
    {
      name: 'Linen Cotton Blend Saree',
      slug: 'linen-cotton-blend-saree',
      description: 'Contemporary linen-cotton blend saree in solid tones with a woven border. Wrinkle-resistant and perfect for office wear.',
      shortDescription: 'Wrinkle-resistant linen-cotton for office and casual wear.',
      productType: 'clothing', category: cottonSarCat._id,
      collections: [officeCol._id, summerCol._id],
      attributes: { fabric: ['Linen', 'Cotton'], occasion: ['Daily Wear'] },
      mrp: 1799, salePrice: 1299, discountPercentage: disc(1799, 1299),
      images: [IMG.ethnic2], tags: ['linen', 'office', 'summer'],
      isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('CSR-005', ['Beige', 'White', 'Blue', 'Green']),
    },

    // ─── DESIGNER SAREES ───────────────────────────────────────────────────
    {
      name: 'Sequin Embellished Georgette Party Saree',
      slug: 'sequin-embellished-georgette-party-saree',
      description: 'Glamorous georgette party saree with all-over sequin embellishment and a ready-to-wear blouse. Available in stunning party shades.',
      shortDescription: 'All-over sequin georgette for glamorous parties.',
      productType: 'clothing', category: designerSarCat._id,
      collections: [newArrivalsCol._id, diwaliCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Party', 'Festive'] },
      mrp: 8999, salePrice: 5999, discountPercentage: disc(8999, 5999),
      images: [IMG.ethnic1], tags: ['sequin', 'georgette', 'party', 'reception'],
      isTrending: true, isNewArrival: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('DSR-001', ['Gold', 'Red', 'Pink', 'Blue']),
    },
    {
      name: 'Pre-Stitched Ruffle Saree',
      slug: 'pre-stitched-ruffle-saree',
      description: 'Modern pre-stitched ruffle saree in soft chiffon — no draping required. Available in pastel and bold shades.',
      shortDescription: 'No-drape pre-stitched ruffle chiffon saree.',
      productType: 'clothing', category: designerSarCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Chiffon'], occasion: ['Party'] },
      mrp: 6999, salePrice: 4999, discountPercentage: disc(6999, 4999),
      images: [IMG.ethnic2], tags: ['ruffle', 'pre-stitched', 'modern'],
      isNewArrival: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('DSR-002', ['Pink', 'White', 'Blue', 'Red']),
    },
    {
      name: 'Embroidered Velvet Saree',
      slug: 'embroidered-velvet-saree',
      description: 'Opulent velvet saree with dense floral embroidery in gold thread. Rich texture and heavy fall make it ideal for weddings.',
      shortDescription: 'Opulent velvet with dense gold floral embroidery.',
      productType: 'clothing', category: designerSarCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { fabric: ['Velvet'], occasion: ['Wedding', 'Festive'] },
      mrp: 14999, salePrice: 10999, discountPercentage: disc(14999, 10999),
      images: [IMG.saree1], tags: ['velvet', 'embroidery', 'wedding'],
      isFeatured: true, isBestSeller: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('DSR-003', ['Green', 'Red', 'Blue', 'Pink']),
    },
    {
      name: 'Mirror Work Organza Saree',
      slug: 'mirror-work-organza-saree',
      description: 'Sheer organza saree with hand-stitched mirror work across the pallu and border. Available in vibrant festive shades.',
      shortDescription: 'Sheer organza with hand-stitched mirror work pallu.',
      productType: 'clothing', category: designerSarCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Net'], occasion: ['Festive', 'Party'] },
      mrp: 9999, salePrice: 6999, discountPercentage: disc(9999, 6999),
      images: [IMG.ethnic1], tags: ['mirror work', 'organza', 'festive'],
      isTrending: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('DSR-004', ['Blue', 'Red', 'Green', 'Gold']),
    },
    {
      name: 'Embellished Net Saree with Blouse',
      slug: 'embellished-net-saree-with-blouse',
      description: 'Delicate net saree with pearl and stone embellishment throughout, paired with a heavily embroidered readymade blouse.',
      shortDescription: 'Pearl and stone net saree with embroidered blouse.',
      productType: 'clothing', category: designerSarCat._id,
      collections: [newArrivalsCol._id, weddingCol._id],
      attributes: { fabric: ['Net'], occasion: ['Wedding', 'Party'] },
      mrp: 7999, salePrice: 5499, discountPercentage: disc(7999, 5499),
      images: [IMG.ethnic2], tags: ['net', 'pearl', 'stone', 'blouse included'],
      isNewArrival: true, isActive: true,
      sizeChartId: sareeChart._id,
      variants: freeV('DSR-005', ['White', 'Pink', 'Blue', 'Gold']),
    },

    // ─── KURTIS (3 colors × 4 sizes = 12 variants each) ───────────────────
    {
      name: 'Floral A-Line Cotton Kurti',
      slug: 'floral-a-line-cotton-kurti',
      description: 'Breezy A-line cotton kurti with an all-over floral print. Available in Pink, Blue, and Red. Comfortable fit for daily wear.',
      shortDescription: 'Breezy A-line cotton kurti with all-over floral print.',
      productType: 'clothing', category: kurtiCat._id,
      collections: [summerCol._id, newArrivalsCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1299, salePrice: 899, discountPercentage: disc(1299, 899),
      images: [IMG.western1], tags: ['kurti', 'floral', 'cotton', 'a-line'],
      isNewArrival: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUR-001', ['Pink', 'Blue', 'Red'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Anarkali Festive Georgette Kurti',
      slug: 'anarkali-festive-georgette-kurti',
      description: 'Floor-length Anarkali kurti in soft georgette with embroidered yoke. Available in Red, Pink, and Blue for festive events.',
      shortDescription: 'Floor-length georgette Anarkali with embroidered yoke.',
      productType: 'clothing', category: kurtiCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Festive', 'Party'] },
      mrp: 2499, salePrice: 1799, discountPercentage: disc(2499, 1799),
      images: [IMG.ethnic1], tags: ['anarkali', 'georgette', 'festive'],
      isBestSeller: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUR-002', ['Red', 'Pink', 'Blue'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Straight Cut Office Kurti',
      slug: 'straight-cut-office-kurti',
      description: 'Polished straight-cut kurti in solid rayon with button placket. Available in Blue, Black, and White for professional settings.',
      shortDescription: 'Solid rayon straight-cut kurti for office wear.',
      productType: 'clothing', category: kurtiCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1599, salePrice: 1199, discountPercentage: disc(1599, 1199),
      images: [IMG.western2], tags: ['kurti', 'office', 'straight cut'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUR-003', ['Blue', 'Black', 'White'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Short Embroidered Kurti',
      slug: 'short-embroidered-kurti',
      description: 'Short hip-length kurti with delicate chikankari-inspired embroidery. Available in White, Pink, and Blue.',
      shortDescription: 'Hip-length cotton kurti with chikankari-style embroidery.',
      productType: 'clothing', category: kurtiCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1199, salePrice: 849, discountPercentage: disc(1199, 849),
      images: [IMG.western1], tags: ['kurti', 'embroidered', 'chikankari', 'short'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUR-004', ['White', 'Pink', 'Blue'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Tie-Dye Long Kurti',
      slug: 'tie-dye-long-kurti',
      description: 'Earthy tie-dye cotton long kurti with a relaxed silhouette and side pockets. Available in Beige, Pink, and Green.',
      shortDescription: 'Earthy tie-dye cotton long kurti with side pockets.',
      productType: 'clothing', category: kurtiCat._id,
      collections: [newArrivalsCol._id, summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear', 'Party'] },
      mrp: 1499, salePrice: 999, discountPercentage: disc(1499, 999),
      images: [IMG.western3], tags: ['tie-dye', 'kurti', 'casual', 'trendy'],
      isTrending: true, isNewArrival: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUR-005', ['Beige', 'Pink', 'Green'], ['S', 'M', 'L', 'XL']),
    },

    // ─── KURTA SETS (3 colors × 4 sizes) ──────────────────────────────────
    {
      name: 'Silk Kurta Pyjama Set',
      slug: 'silk-kurta-pyjama-set',
      description: 'Luxurious silk kurta with matching pyjama, featuring subtle butti embroidery. Available in Gold, Red, and Green.',
      shortDescription: 'Silk kurta-pyjama with butti embroidery and contrast piping.',
      productType: 'clothing', category: kurtaSetCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Festive', 'Wedding'] },
      mrp: 3999, salePrice: 2999, discountPercentage: disc(3999, 2999),
      images: [IMG.ethnic1], tags: ['kurta set', 'silk', 'festive', 'pyjama'],
      isFeatured: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUS-001', ['Gold', 'Red', 'Green'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Cotton Kurta Sharara Set',
      slug: 'cotton-kurta-sharara-set',
      description: 'Breezy cotton kurta paired with wide-leg sharara pants. Block printed in earthy tones. Available in Beige, Pink, and Blue.',
      shortDescription: 'Cotton block print kurta with wide-leg sharara pants.',
      productType: 'clothing', category: kurtaSetCat._id,
      collections: [newArrivalsCol._id, summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Festive', 'Daily Wear'] },
      mrp: 2999, salePrice: 2199, discountPercentage: disc(2999, 2199),
      images: [IMG.western2], tags: ['sharara', 'cotton', 'block print'],
      isNewArrival: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUS-002', ['Beige', 'Pink', 'Blue'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Embroidered Palazzo Kurta Set',
      slug: 'embroidered-palazzo-kurta-set',
      description: 'Georgette kurta with floral embroidery on the yoke and hem, paired with matching flared palazzo pants. Available in Pink, Red, and Blue.',
      shortDescription: 'Georgette kurta with floral embroidery and palazzo pants.',
      productType: 'clothing', category: kurtaSetCat._id,
      collections: [festiveCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Festive', 'Party'] },
      mrp: 3499, salePrice: 2499, discountPercentage: disc(3499, 2499),
      images: [IMG.ethnic2], tags: ['palazzo', 'embroidered', 'georgette'],
      isBestSeller: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUS-003', ['Pink', 'Red', 'Blue'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Block Print Pant Kurta Set',
      slug: 'block-print-pant-kurta-set',
      description: 'Hand block printed kurta in Jaipur style with straight pants. Available in Blue, Green, and Beige.',
      shortDescription: 'Jaipur hand block print kurta with straight pants.',
      productType: 'clothing', category: kurtaSetCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 2499, salePrice: 1799, discountPercentage: disc(2499, 1799),
      images: [IMG.western1], tags: ['block print', 'pant kurta', 'jaipur'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUS-004', ['Blue', 'Green', 'Beige'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Festive Anarkali Kurta Set',
      slug: 'festive-anarkali-kurta-set',
      description: 'Floor-grazing Anarkali kurta in georgette with churidar and dupatta. Available in Red, Pink, and Blue.',
      shortDescription: 'Floor-length georgette Anarkali with churidar and dupatta.',
      productType: 'clothing', category: kurtaSetCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Festive', 'Party'] },
      mrp: 4999, salePrice: 3499, discountPercentage: disc(4999, 3499),
      images: [IMG.ethnic1], tags: ['anarkali', 'festive', 'churidar', 'dupatta'],
      isFeatured: true, isBestSeller: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('KUS-005', ['Red', 'Pink', 'Blue'], ['S', 'M', 'L', 'XL']),
    },

    // ─── LEHENGAS (3 colors × 3 sizes) ────────────────────────────────────
    {
      name: 'Bridal Red Silk Lehenga Choli',
      slug: 'bridal-red-silk-lehenga-choli',
      description: 'Heavy bridal lehenga in pure silk with intricate zardozi embroidery and organza dupatta. Available in Red, Pink, and Gold.',
      shortDescription: 'Heavy zardozi silk bridal lehenga with organza dupatta.',
      productType: 'clothing', category: lehengaCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Bridal', 'Wedding'] },
      mrp: 24999, salePrice: 18999, discountPercentage: disc(24999, 18999),
      images: [IMG.lehenga1], tags: ['bridal', 'lehenga', 'zardozi', 'silk'],
      isFeatured: true, isBestSeller: true, isActive: true,
      sizeChartId: lehenasChart._id,
      variants: makeV('LEH-001', ['Red', 'Pink', 'Gold'], ['S', 'M', 'L']),
    },
    {
      name: 'Pink Net Festive Lehenga',
      slug: 'pink-net-festive-lehenga',
      description: 'Pastel multi-tiered net lehenga with sequin embroidery and a matching organza dupatta. Available in Pink, Red, and Blue.',
      shortDescription: 'Pastel pink multi-tiered net lehenga with sequins.',
      productType: 'clothing', category: lehengaCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Net'], occasion: ['Festive', 'Party'] },
      mrp: 9999, salePrice: 6999, discountPercentage: disc(9999, 6999),
      images: [IMG.ethnic2], tags: ['lehenga', 'pink', 'net', 'sangeet'],
      isTrending: true, isActive: true,
      sizeChartId: lehenasChart._id,
      variants: makeV('LEH-002', ['Pink', 'Red', 'Blue'], ['S', 'M', 'L']),
    },
    {
      name: 'Sequin Party Lehenga',
      slug: 'sequin-party-lehenga',
      description: 'Dazzling sequin-work lehenga on a net base with a fully embellished blouse. Available in Gold, Red, and Pink.',
      shortDescription: 'Fully sequined net lehenga for parties and receptions.',
      productType: 'clothing', category: lehengaCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Net'], occasion: ['Party', 'Festive'] },
      mrp: 14999, salePrice: 9999, discountPercentage: disc(14999, 9999),
      images: [IMG.lehenga1], tags: ['sequin', 'lehenga', 'party'],
      isNewArrival: true, isActive: true,
      sizeChartId: lehenasChart._id,
      variants: makeV('LEH-003', ['Gold', 'Red', 'Pink'], ['S', 'M', 'L']),
    },
    {
      name: 'Pastel Embroidered Wedding Lehenga',
      slug: 'pastel-embroidered-wedding-lehenga',
      description: 'Romantic pastel lehenga with delicate thread embroidery and a flared silhouette. Available in Green, Blue, and Pink.',
      shortDescription: 'Pastel mint lehenga with delicate thread embroidery.',
      productType: 'clothing', category: lehengaCat._id,
      collections: [weddingCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Wedding', 'Festive'] },
      mrp: 12999, salePrice: 8999, discountPercentage: disc(12999, 8999),
      images: [IMG.ethnic1], tags: ['lehenga', 'pastel', 'embroidered', 'reception'],
      isFeatured: true, isActive: true,
      sizeChartId: lehenasChart._id,
      variants: makeV('LEH-004', ['Green', 'Blue', 'Pink'], ['S', 'M', 'L']),
    },
    {
      name: 'Palazzo Style Festive Lehenga',
      slug: 'palazzo-style-festive-lehenga',
      description: 'Contemporary palazzo-cut lehenga in georgette with mirror work detailing. Available in Blue, Pink, and Green.',
      shortDescription: 'Wide-leg palazzo lehenga in georgette with mirror work.',
      productType: 'clothing', category: lehengaCat._id,
      collections: [festiveCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Festive'] },
      mrp: 7999, salePrice: 5499, discountPercentage: disc(7999, 5499),
      images: [IMG.ethnic2], tags: ['palazzo', 'lehenga', 'mirror work'],
      isActive: true,
      sizeChartId: lehenasChart._id,
      variants: makeV('LEH-005', ['Blue', 'Pink', 'Green'], ['S', 'M', 'L']),
    },

    // ─── SALWAR SUITS (3 colors × 4 sizes) ────────────────────────────────
    {
      name: 'Cotton Patiala Salwar Suit',
      slug: 'cotton-patiala-salwar-suit',
      description: 'Classic Punjabi-style Patiala salwar suit in pure cotton with printed dupatta. Available in Pink, Blue, and Red.',
      shortDescription: 'Classic Punjabi Patiala salwar in pure cotton with dupatta.',
      productType: 'clothing', category: salwarCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1999, salePrice: 1399, discountPercentage: disc(1999, 1399),
      images: [IMG.western1], tags: ['patiala', 'cotton', 'salwar', 'punjabi'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('SAL-001', ['Pink', 'Blue', 'Red'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Georgette Anarkali Suit',
      slug: 'georgette-anarkali-suit',
      description: 'Flowy georgette Anarkali suit with heavy embroidered yoke and matching churidar. Available in Red, Pink, and Blue.',
      shortDescription: 'Flowy georgette Anarkali with embroidered yoke and churidar.',
      productType: 'clothing', category: salwarCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Festive', 'Party'] },
      mrp: 3499, salePrice: 2499, discountPercentage: disc(3499, 2499),
      images: [IMG.ethnic1], tags: ['anarkali', 'georgette', 'festive'],
      isBestSeller: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('SAL-002', ['Red', 'Pink', 'Blue'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Churidar Printed Cotton Suit',
      slug: 'churidar-printed-cotton-suit',
      description: 'Printed cotton straight kurta with churidar and dupatta. Available in Blue, Green, and White.',
      shortDescription: 'Printed cotton straight kurta with churidar dupatta set.',
      productType: 'clothing', category: salwarCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1499, salePrice: 999, discountPercentage: disc(1499, 999),
      images: [IMG.western2], tags: ['churidar', 'printed', 'cotton', 'office'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('SAL-003', ['Blue', 'Green', 'White'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Straight Silk Salwar Suit',
      slug: 'straight-silk-salwar-suit',
      description: 'Elegant straight-cut silk suit with contrast silk dupatta and embroidered border. Available in Green, Blue, and Pink.',
      shortDescription: 'Straight-cut silk suit with embroidered border and dupatta.',
      productType: 'clothing', category: salwarCat._id,
      collections: [festiveCol._id, weddingCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Festive', 'Wedding'] },
      mrp: 4999, salePrice: 3499, discountPercentage: disc(4999, 3499),
      images: [IMG.ethnic2], tags: ['silk', 'straight suit', 'festive'],
      isFeatured: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('SAL-004', ['Green', 'Blue', 'Pink'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Embroidered Party Salwar Suit',
      slug: 'embroidered-party-salwar-suit',
      description: 'Semi-stitched georgette party suit with heavy embroidery and flowing palazzos. Available in Pink, Red, and Blue.',
      shortDescription: 'Heavy embroidered georgette suit with palazzo and dupatta.',
      productType: 'clothing', category: salwarCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Party', 'Festive'] },
      mrp: 5999, salePrice: 3999, discountPercentage: disc(5999, 3999),
      images: [IMG.ethnic1], tags: ['embroidered', 'party', 'palazzo'],
      isNewArrival: true, isTrending: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('SAL-005', ['Pink', 'Red', 'Blue'], ['S', 'M', 'L', 'XL']),
    },

    // ─── TOPS (3 colors × 4 sizes) ─────────────────────────────────────────
    {
      name: 'Printed Crop Top',
      slug: 'printed-crop-top',
      description: 'Vibrant tropical-print crop top in soft cotton. Available in Pink, White, and Blue.',
      shortDescription: 'Tropical print soft cotton crop top for casual outings.',
      productType: 'clothing', category: topCat._id,
      collections: [summerCol._id, newArrivalsCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear', 'Party'] },
      mrp: 799, salePrice: 549, discountPercentage: disc(799, 549),
      images: [IMG.western3], tags: ['crop top', 'printed', 'summer', 'casual'],
      isNewArrival: true, isTrending: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('TOP-001', ['Pink', 'White', 'Blue'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Off-Shoulder Embroidered Top',
      slug: 'off-shoulder-embroidered-top',
      description: 'Breezy off-shoulder cotton top with floral embroidery on the neckline. Available in White, Pink, and Blue.',
      shortDescription: 'Off-shoulder cotton top with floral neckline embroidery.',
      productType: 'clothing', category: topCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Party', 'Daily Wear'] },
      mrp: 1199, salePrice: 849, discountPercentage: disc(1199, 849),
      images: [IMG.western1], tags: ['off-shoulder', 'embroidered', 'top'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('TOP-002', ['White', 'Pink', 'Blue'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Satin Slip Top',
      slug: 'satin-slip-top',
      description: 'Sleek satin slip top with thin straps and a bias-cut hem. Available in Black, White, and Blue.',
      shortDescription: 'Bias-cut satin slip top for elegant evenings.',
      productType: 'clothing', category: topCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Satin'], occasion: ['Party'] },
      mrp: 1499, salePrice: 999, discountPercentage: disc(1499, 999),
      images: [IMG.western2], tags: ['satin', 'slip top', 'party'],
      isTrending: true, isNewArrival: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('TOP-003', ['Black', 'White', 'Blue'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Peplum Crepe Blouse Top',
      slug: 'peplum-crepe-blouse-top',
      description: 'Structured peplum blouse top in crepe with a flattering flare at the waist. Available in Blue, Black, and White.',
      shortDescription: 'Structured crepe peplum top for polished office looks.',
      productType: 'clothing', category: topCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Crepe'], occasion: ['Daily Wear'] },
      mrp: 1299, salePrice: 899, discountPercentage: disc(1299, 899),
      images: [IMG.western3], tags: ['peplum', 'crepe', 'office', 'blouse'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('TOP-004', ['Blue', 'Black', 'White'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Tie-Dye Festival Top',
      slug: 'tie-dye-festival-top',
      description: 'Fun tie-dye cotton festival top in boho colours with fringe detail. Available in Blue, Pink, and Green.',
      shortDescription: 'Boho tie-dye cotton top with fringe detail for festivals.',
      productType: 'clothing', category: topCat._id,
      collections: [summerCol._id, festiveCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Festive', 'Daily Wear'] },
      mrp: 899, salePrice: 599, discountPercentage: disc(899, 599),
      images: [IMG.western1], tags: ['tie-dye', 'festival', 'boho'],
      isTrending: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('TOP-005', ['Blue', 'Pink', 'Green'], ['XS', 'S', 'M', 'L']),
    },

    // ─── DRESSES (3 colors × 4 sizes) ─────────────────────────────────────
    {
      name: 'Floral Georgette Maxi Dress',
      slug: 'floral-georgette-maxi-dress',
      description: 'Floor-length maxi dress in flowy georgette with an all-over floral print. Available in Pink, Blue, and White.',
      shortDescription: 'Flowy floral georgette floor-length maxi dress.',
      productType: 'clothing', category: dressCat._id,
      collections: [summerCol._id, newArrivalsCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Party', 'Daily Wear'] },
      mrp: 2999, salePrice: 1999, discountPercentage: disc(2999, 1999),
      images: [IMG.western3], tags: ['maxi', 'floral', 'georgette', 'summer'],
      isNewArrival: true, isTrending: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('DRS-001', ['Pink', 'Blue', 'White'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Bodycon Crepe Party Dress',
      slug: 'bodycon-crepe-party-dress',
      description: 'Figure-hugging bodycon dress in stretch crepe with a square neckline. Available in Black, Red, and Blue.',
      shortDescription: 'Stretch crepe bodycon dress with square neckline.',
      productType: 'clothing', category: dressCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Crepe'], occasion: ['Party'] },
      mrp: 2499, salePrice: 1699, discountPercentage: disc(2499, 1699),
      images: [IMG.western2], tags: ['bodycon', 'party', 'crepe', 'black'],
      isNewArrival: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('DRS-002', ['Black', 'Red', 'Blue'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'A-Line Casual Cotton Dress',
      slug: 'a-line-casual-cotton-dress',
      description: 'Easy-fit A-line cotton dress with a smocked bodice and tiered skirt. Available in White, Pink, and Blue.',
      shortDescription: 'Smocked A-line cotton dress with tiered skirt.',
      productType: 'clothing', category: dressCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1799, salePrice: 1199, discountPercentage: disc(1799, 1199),
      images: [IMG.western1], tags: ['a-line', 'casual', 'cotton', 'smocked'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('DRS-003', ['White', 'Pink', 'Blue'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Midi Wrap Dress in Georgette',
      slug: 'midi-wrap-dress-georgette',
      description: 'Sophisticated midi-length wrap dress in floral georgette. Available in Blue, Green, and Pink.',
      shortDescription: 'Floral georgette midi wrap dress with adjustable waist.',
      productType: 'clothing', category: dressCat._id,
      collections: [officeCol._id, summerCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Party', 'Daily Wear'] },
      mrp: 2199, salePrice: 1499, discountPercentage: disc(2199, 1499),
      images: [IMG.western3], tags: ['wrap dress', 'midi', 'georgette'],
      isBestSeller: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('DRS-004', ['Blue', 'Green', 'Pink'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Pinstripe Cotton Shirt Dress',
      slug: 'pinstripe-cotton-shirt-dress',
      description: 'Classic pinstripe cotton shirt dress with a button-down front and belted waist. Available in White, Blue, and Black.',
      shortDescription: 'Pinstripe cotton shirt dress with belted waist.',
      productType: 'clothing', category: dressCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1999, salePrice: 1399, discountPercentage: disc(1999, 1399),
      images: [IMG.western2], tags: ['shirt dress', 'pinstripe', 'office', 'cotton'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('DRS-005', ['White', 'Blue', 'Black'], ['XS', 'S', 'M', 'L']),
    },

    // ─── JEANS & TROUSERS (2 colors × 4 sizes) ────────────────────────────
    {
      name: 'Skinny Stretch High-Waist Jeans',
      slug: 'skinny-stretch-high-waist-jeans',
      description: 'High-waist skinny jeans in 4-way stretch denim with a figure-hugging fit. Available in Blue and Black.',
      shortDescription: 'High-waist 4-way stretch skinny jeans in classic blue.',
      productType: 'clothing', category: jeansCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear', 'Party'] },
      mrp: 1999, salePrice: 1299, discountPercentage: disc(1999, 1299),
      images: [IMG.western3], tags: ['jeans', 'skinny', 'high waist', 'denim'],
      isBestSeller: true, isActive: true,
      sizeChartId: pantsChart._id,
      variants: makeV('JNT-001', ['Blue', 'Black'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'High-Waist Flared Trousers',
      slug: 'high-waist-flared-trousers',
      description: 'Chic high-waist flared trousers in structured crepe. Available in Black and Blue.',
      shortDescription: 'Structured crepe high-waist flared trousers.',
      productType: 'clothing', category: jeansCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Crepe'], occasion: ['Daily Wear', 'Party'] },
      mrp: 2499, salePrice: 1699, discountPercentage: disc(2499, 1699),
      images: [IMG.western2], tags: ['flared', 'trousers', 'crepe', 'office'],
      isTrending: true, isActive: true,
      sizeChartId: pantsChart._id,
      variants: makeV('JNT-002', ['Black', 'Blue', 'White'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Cotton Jogger Pants',
      slug: 'cotton-jogger-pants',
      description: 'Relaxed-fit jogger pants in soft cotton jersey with elasticated waist and tapered ankles. Available in Black, Blue, and Pink.',
      shortDescription: 'Soft cotton jersey joggers with elasticated waist.',
      productType: 'clothing', category: jeansCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Daily Wear'] },
      mrp: 1299, salePrice: 899, discountPercentage: disc(1299, 899),
      images: [IMG.western1], tags: ['joggers', 'cotton', 'casual', 'comfort'],
      isActive: true,
      sizeChartId: pantsChart._id,
      variants: makeV('JNT-003', ['Black', 'Blue', 'Pink'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Wide-Leg Georgette Palazzos',
      slug: 'wide-leg-georgette-palazzos',
      description: 'Flowy wide-leg palazzo pants in printed georgette with an elasticated waist. Available in Pink, Blue, and White.',
      shortDescription: 'Flowy printed georgette palazzo with elasticated waist.',
      productType: 'clothing', category: jeansCat._id,
      collections: [summerCol._id, festiveCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Daily Wear', 'Party'] },
      mrp: 1799, salePrice: 1199, discountPercentage: disc(1799, 1199),
      images: [IMG.ethnic2], tags: ['palazzo', 'wide leg', 'georgette'],
      isActive: true,
      sizeChartId: pantsChart._id,
      variants: makeV('JNT-004', ['Pink', 'Blue', 'White'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Straight Cut Formal Trouser',
      slug: 'straight-cut-formal-trouser',
      description: 'Tailored straight-cut trouser in poly-crepe with a mid-rise waist and clean front pleat. Available in Black, White, and Blue.',
      shortDescription: 'Tailored poly-crepe straight-cut trouser for workwear.',
      productType: 'clothing', category: jeansCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Crepe'], occasion: ['Daily Wear'] },
      mrp: 2199, salePrice: 1499, discountPercentage: disc(2199, 1499),
      images: [IMG.western3], tags: ['formal', 'trouser', 'straight cut', 'office'],
      isActive: true,
      sizeChartId: pantsChart._id,
      variants: makeV('JNT-005', ['Black', 'White', 'Blue'], ['XS', 'S', 'M', 'L']),
    },

    // ─── CO-ORD SETS (3 colors × 4 sizes) ─────────────────────────────────
    {
      name: 'Floral Georgette Co-Ord Set',
      slug: 'floral-georgette-coord-set',
      description: 'Matching crop top and flared skirt co-ord set in floral georgette. Available in Pink, Blue, and White.',
      shortDescription: 'Floral georgette crop top and flared skirt co-ord.',
      productType: 'clothing', category: coordCat._id,
      collections: [newArrivalsCol._id, festiveCol._id],
      attributes: { fabric: ['Georgette'], occasion: ['Party', 'Festive'] },
      mrp: 3499, salePrice: 2299, discountPercentage: disc(3499, 2299),
      images: [IMG.western2], tags: ['co-ord', 'floral', 'georgette', 'skirt set'],
      isNewArrival: true, isTrending: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('CRD-001', ['Pink', 'Blue', 'White'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Printed Crop Top and Mini Skirt Set',
      slug: 'printed-crop-top-mini-skirt-set',
      description: 'Bold geometric-print crop top and matching mini skirt co-ord. Available in White, Pink, and Blue.',
      shortDescription: 'Geometric print crop top and mini skirt co-ord.',
      productType: 'clothing', category: coordCat._id,
      collections: [summerCol._id],
      attributes: { fabric: ['Cotton'], occasion: ['Party', 'Daily Wear'] },
      mrp: 2999, salePrice: 1999, discountPercentage: disc(2999, 1999),
      images: [IMG.western1], tags: ['co-ord', 'printed', 'mini skirt', 'crop'],
      isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('CRD-002', ['White', 'Pink', 'Blue'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Ethnic Mirror Work Co-Ord Set',
      slug: 'ethnic-mirror-work-coord-set',
      description: 'Festive-ready ethnic co-ord with mirror-embellished kurta top and matching wide-leg pants. Available in Red, Blue, and Green.',
      shortDescription: 'Mirror-embellished ethnic kurta and wide-leg pant set.',
      productType: 'clothing', category: coordCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { fabric: ['Silk'], occasion: ['Festive', 'Party'] },
      mrp: 4999, salePrice: 3299, discountPercentage: disc(4999, 3299),
      images: [IMG.ethnic1], tags: ['mirror work', 'ethnic', 'co-ord', 'rajasthani'],
      isFeatured: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('CRD-003', ['Red', 'Blue', 'Green'], ['S', 'M', 'L', 'XL']),
    },
    {
      name: 'Solid Blazer Co-Ord Set',
      slug: 'solid-blazer-coord-set',
      description: 'Power-dressing blazer and straight trouser co-ord in solid poly-crepe. Available in Black, Blue, and White.',
      shortDescription: 'Tailored blazer and trouser power co-ord for office.',
      productType: 'clothing', category: coordCat._id,
      collections: [officeCol._id],
      attributes: { fabric: ['Crepe'], occasion: ['Daily Wear'] },
      mrp: 5999, salePrice: 3999, discountPercentage: disc(5999, 3999),
      images: [IMG.western3], tags: ['blazer', 'co-ord', 'office', 'corporate'],
      isBestSeller: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('CRD-004', ['Black', 'Blue', 'White'], ['XS', 'S', 'M', 'L']),
    },
    {
      name: 'Solid Crop Top and Skirt Co-Ord',
      slug: 'solid-crop-top-skirt-coord',
      description: 'Clean minimal co-ord with a solid crop top and a flared midi skirt in matching satin. Available in Beige, Pink, and White.',
      shortDescription: 'Minimal satin crop top and flared midi skirt co-ord.',
      productType: 'clothing', category: coordCat._id,
      collections: [newArrivalsCol._id],
      attributes: { fabric: ['Satin'], occasion: ['Party', 'Daily Wear'] },
      mrp: 3999, salePrice: 2699, discountPercentage: disc(3999, 2699),
      images: [IMG.western2], tags: ['co-ord', 'satin', 'minimal', 'midi skirt'],
      isNewArrival: true, isActive: true,
      sizeChartId: kurtisChart._id,
      variants: makeV('CRD-005', ['Beige', 'Pink', 'White'], ['XS', 'S', 'M', 'L']),
    },

    // ─── NECKLACES ─────────────────────────────────────────────────────────
    {
      name: 'Kundan Bridal Necklace Set',
      slug: 'kundan-bridal-necklace-set',
      description: 'Opulent kundan bridal necklace set with matching earrings and maangtikka. Set in 1-gram gold with meenakari reverse.',
      shortDescription: '1-gram gold kundan bridal necklace with earrings and tikka.',
      productType: 'jewellery', category: necklaceCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { metal: ['1 Gram Gold'], purity: ['Gold Plated'], occasion: ['Bridal', 'Wedding'] },
      mrp: 4999, salePrice: 3499, discountPercentage: disc(4999, 3499),
      images: [IMG.jewel1], tags: ['kundan', 'bridal', 'necklace set', '1 gram gold'],
      isFeatured: true, isBestSeller: true, isActive: true,
      variants: [{ sku: 'NEC-001-OS', stock: 20, attributes: { color: 'Gold' } }],
    },
    {
      name: 'Temple Jewellery Long Necklace',
      slug: 'temple-jewellery-long-necklace',
      description: 'Traditional South Indian temple jewellery long necklace in 1-gram gold with deity motifs and ruby-red stones.',
      shortDescription: 'South Indian temple motif long necklace in 1-gram gold.',
      productType: 'jewellery', category: necklaceCat._id,
      collections: [festiveCol._id],
      attributes: { metal: ['1 Gram Gold'], purity: ['Gold Plated'], occasion: ['Festive', 'Wedding'] },
      mrp: 3999, salePrice: 2799, discountPercentage: disc(3999, 2799),
      images: [IMG.jewel2], tags: ['temple jewellery', 'south indian', 'long necklace'],
      isActive: true,
      variants: [{ sku: 'NEC-002-OS', stock: 18, attributes: { color: 'Gold' } }],
    },
    {
      name: 'Silver Oxidised Statement Necklace',
      slug: 'silver-oxidised-statement-necklace',
      description: 'Bold silver oxidised statement necklace with tribal motifs and turquoise stone accents. Pairs well with kurtis and ethnic wear.',
      shortDescription: 'Bold oxidised silver tribal necklace with turquoise accents.',
      productType: 'jewellery', category: necklaceCat._id,
      collections: [newArrivalsCol._id],
      attributes: { metal: ['Original Silver'], purity: ['92.5 Silver'], occasion: ['Festive', 'Daily Wear'] },
      mrp: 1999, salePrice: 1299, discountPercentage: disc(1999, 1299),
      images: [IMG.jewel3], tags: ['silver', 'oxidised', 'tribal', 'statement'],
      isNewArrival: true, isTrending: true, isActive: true,
      variants: [{ sku: 'NEC-003-OS', stock: 25, attributes: { color: 'White' } }],
    },
    {
      name: 'Rolled Gold Choker Necklace',
      slug: 'rolled-gold-choker-necklace',
      description: 'Elegant rolled gold choker necklace with floral motifs and CZ stones. Versatile for both ethnic and indo-western outfits.',
      shortDescription: 'Rolled gold choker with floral CZ stone motifs.',
      productType: 'jewellery', category: necklaceCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { metal: ['Rolled Gold'], purity: ['Gold Plated'], occasion: ['Festive', 'Party'] },
      mrp: 2499, salePrice: 1699, discountPercentage: disc(2499, 1699),
      images: [IMG.jewel1], tags: ['choker', 'rolled gold', 'CZ', 'floral'],
      isTrending: true, isActive: true,
      variants: [{ sku: 'NEC-004-OS', stock: 22, attributes: { color: 'Gold' } }],
    },
    {
      name: 'Pearl Layered Necklace',
      slug: 'pearl-layered-necklace',
      description: 'Multi-strand layered pearl necklace with a gold-tone clasp. Timeless design suitable for daily wear and formal occasions.',
      shortDescription: 'Multi-strand layered pearl necklace with gold clasp.',
      productType: 'jewellery', category: necklaceCat._id,
      collections: [officeCol._id],
      attributes: { metal: ['Imitation'], purity: ['Gold Plated'], occasion: ['Daily Wear', 'Festive'] },
      mrp: 1499, salePrice: 999, discountPercentage: disc(1499, 999),
      images: [IMG.jewel2], tags: ['pearl', 'layered', 'necklace'],
      isActive: true,
      variants: [{ sku: 'NEC-005-OS', stock: 30, attributes: { color: 'White' } }],
    },

    // ─── EARRINGS ──────────────────────────────────────────────────────────
    {
      name: 'Jhumka Gold Plated Earrings',
      slug: 'jhumka-gold-plated-earrings',
      description: 'Classic bell-shaped jhumka earrings in 1-gram gold with ruby-red and green enamel work.',
      shortDescription: 'Classic 1-gram gold jhumka with enamel colour work.',
      productType: 'jewellery', category: earringCat._id,
      collections: [festiveCol._id],
      attributes: { metal: ['1 Gram Gold'], purity: ['Gold Plated'], occasion: ['Festive', 'Wedding'] },
      mrp: 899, salePrice: 599, discountPercentage: disc(899, 599),
      images: [IMG.jewel1], tags: ['jhumka', 'gold', 'festive', 'enamel'],
      isBestSeller: true, isActive: true,
      variants: [{ sku: 'EAR-001-OS', stock: 40, attributes: { color: 'Gold' } }],
    },
    {
      name: 'Pearl Drop Earrings',
      slug: 'pearl-drop-earrings',
      description: 'Delicate freshwater pearl drop earrings with a gold-plated stud base. Elegant and lightweight for everyday use.',
      shortDescription: 'Delicate freshwater pearl drop earrings with gold stud.',
      productType: 'jewellery', category: earringCat._id,
      collections: [officeCol._id],
      attributes: { metal: ['Imitation'], purity: ['Gold Plated'], occasion: ['Daily Wear'] },
      mrp: 699, salePrice: 449, discountPercentage: disc(699, 449),
      images: [IMG.jewel2], tags: ['pearl', 'drop earrings', 'everyday'],
      isActive: true,
      variants: [{ sku: 'EAR-002-OS', stock: 45, attributes: { color: 'White' } }],
    },
    {
      name: 'Silver Oxidised Chandbali Earrings',
      slug: 'silver-oxidised-chandbali-earrings',
      description: 'Large crescent-shaped chandbali earrings in 92.5 oxidised silver with intricate filigree work and a pearl drop.',
      shortDescription: '92.5 oxidised silver chandbali with filigree and pearl drop.',
      productType: 'jewellery', category: earringCat._id,
      collections: [newArrivalsCol._id, festiveCol._id],
      attributes: { metal: ['Original Silver'], purity: ['92.5 Silver'], occasion: ['Festive', 'Party'] },
      mrp: 1299, salePrice: 899, discountPercentage: disc(1299, 899),
      images: [IMG.jewel3], tags: ['chandbali', 'silver', 'filigree', 'oxidised'],
      isNewArrival: true, isTrending: true, isActive: true,
      variants: [{ sku: 'EAR-003-OS', stock: 28, attributes: { color: 'White' } }],
    },
    {
      name: 'Kundan Stud Earrings',
      slug: 'kundan-stud-earrings',
      description: 'Geometric kundan stud earrings with emerald-green stone centre in 1-gram gold setting. Compact and versatile.',
      shortDescription: 'Geometric 1-gram gold kundan studs with green stone.',
      productType: 'jewellery', category: earringCat._id,
      collections: [festiveCol._id],
      attributes: { metal: ['1 Gram Gold'], purity: ['Gold Plated'], occasion: ['Festive', 'Daily Wear'] },
      mrp: 799, salePrice: 549, discountPercentage: disc(799, 549),
      images: [IMG.jewel1], tags: ['kundan', 'studs', 'gold', 'compact'],
      isActive: true,
      variants: [{ sku: 'EAR-004-OS', stock: 35, attributes: { color: 'Gold' } }],
    },
    {
      name: 'Long Tassel Party Earrings',
      slug: 'long-tassel-party-earrings',
      description: 'Statement long tassel earrings with a jewelled top and silk thread tassel in rich jewel tones. Perfect for parties.',
      shortDescription: 'Statement jewelled top with long silk thread tassel.',
      productType: 'jewellery', category: earringCat._id,
      collections: [newArrivalsCol._id, diwaliCol._id],
      attributes: { metal: ['Imitation'], purity: ['Gold Plated'], occasion: ['Party', 'Festive'] },
      mrp: 599, salePrice: 399, discountPercentage: disc(599, 399),
      images: [IMG.jewel2], tags: ['tassel', 'party earrings', 'statement'],
      isTrending: true, isActive: true,
      variants: [{ sku: 'EAR-005-OS', stock: 38, attributes: { color: 'Red' } }],
    },

    // ─── BANGLES (S/M/L wrist sizes) ───────────────────────────────────────
    {
      name: 'Gold Plated Bangle Set of 6',
      slug: 'gold-plated-bangle-set-6',
      description: 'Set of 6 intricately carved 1-gram gold bangles with floral and paisley engravings. Available in S, M, L wrist sizes.',
      shortDescription: 'Set of 6 carved 1-gram gold bangles with paisley motifs.',
      productType: 'jewellery', category: bangleCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { metal: ['1 Gram Gold'], purity: ['Gold Plated'], occasion: ['Bridal', 'Wedding'] },
      mrp: 2999, salePrice: 1999, discountPercentage: disc(2999, 1999),
      images: [IMG.jewel1], tags: ['bangles', '1 gram gold', 'bridal', 'set of 6'],
      isFeatured: true, isBestSeller: true, isActive: true,
      sizeChartId: banglesChart._id,
      variants: banV('BAN-001', 'Gold'),
    },
    {
      name: 'Silver Kangan Bangle Pair',
      slug: 'silver-kangan-bangle-pair',
      description: 'Pair of traditional 92.5 pure silver kangan bangles with hammered texture. Available in S, M, L wrist sizes.',
      shortDescription: 'Hallmarked 92.5 silver kangan pair with hammered texture.',
      productType: 'jewellery', category: bangleCat._id,
      collections: [festiveCol._id],
      attributes: { metal: ['Original Silver'], purity: ['92.5 Silver'], occasion: ['Festive', 'Wedding'] },
      mrp: 2499, salePrice: 1699, discountPercentage: disc(2499, 1699),
      images: [IMG.jewel3], tags: ['silver', 'kangan', 'hallmarked', 'pure silver'],
      isActive: true,
      sizeChartId: banglesChart._id,
      variants: banV('BAN-002', 'White'),
    },
    {
      name: 'Lac Bangles Festive Set of 12',
      slug: 'lac-bangles-festive-set-12',
      description: 'Vibrant set of 12 traditional Rajasthani lac bangles with mirror, bead, and zari work. Available in S, M, L sizes.',
      shortDescription: 'Set of 12 Rajasthani lac bangles with mirror and zari work.',
      productType: 'jewellery', category: bangleCat._id,
      collections: [festiveCol._id, diwaliCol._id],
      attributes: { metal: ['Imitation'], occasion: ['Festive', 'Return Gift'] },
      mrp: 899, salePrice: 599, discountPercentage: disc(899, 599),
      images: [IMG.jewel2], tags: ['lac bangles', 'rajasthani', 'festive', 'set of 12'],
      isTrending: true, isActive: true,
      sizeChartId: banglesChart._id,
      variants: banV('BAN-003', 'Red'),
    },
    {
      name: 'Stone Studded Rolled Gold Bangles',
      slug: 'stone-studded-rolled-gold-bangles',
      description: 'Set of 4 rolled gold bangles with CZ stone studs in a floral pattern. Available in S, M, L wrist sizes.',
      shortDescription: 'Set of 4 rolled gold bangles with CZ floral stone studs.',
      productType: 'jewellery', category: bangleCat._id,
      collections: [newArrivalsCol._id],
      attributes: { metal: ['Rolled Gold'], purity: ['Gold Plated'], occasion: ['Festive', 'Party'] },
      mrp: 1999, salePrice: 1299, discountPercentage: disc(1999, 1299),
      images: [IMG.jewel1], tags: ['rolled gold', 'CZ stone', 'bangles', 'set of 4'],
      isNewArrival: true, isActive: true,
      sizeChartId: banglesChart._id,
      variants: banV('BAN-004', 'Gold'),
    },
    {
      name: 'Antique Gold Kada Bangles Pair',
      slug: 'antique-gold-kada-bangles-pair',
      description: 'Pair of wide antique gold finish kada bangles with carved temple motifs. Available in S, M, L wrist sizes.',
      shortDescription: 'Wide antique gold kadas with carved temple motifs.',
      productType: 'jewellery', category: bangleCat._id,
      collections: [weddingCol._id, bridalCol._id],
      attributes: { metal: ['1 Gram Gold'], purity: ['Gold Plated'], occasion: ['Bridal', 'Wedding'] },
      mrp: 2999, salePrice: 1999, discountPercentage: disc(2999, 1999),
      images: [IMG.jewel3], tags: ['kada', 'antique gold', 'bridal', 'wide'],
      isBestSeller: true, isActive: true,
      sizeChartId: banglesChart._id,
      variants: banV('BAN-005', 'Gold'),
    },

    // ─── RETURN GIFTS ──────────────────────────────────────────────────────
    {
      name: 'Sindoor Box Return Gift Set',
      slug: 'sindoor-box-return-gift-set',
      description: 'Elegant sindoor dani (box) with a traditional design in 1-gram gold finish, packaged in an organza gift bag.',
      shortDescription: '1-gram gold finish sindoor dani in organza gift bag.',
      productType: 'return-gift', category: returnGiftCat._id,
      collections: [weddingCol._id],
      attributes: { metal: ['1 Gram Gold'], occasion: ['Return Gift', 'Wedding'] },
      mrp: 499, salePrice: 349, discountPercentage: disc(499, 349),
      images: [IMG.gift1], tags: ['sindoor box', 'return gift', 'wedding', 'puja'],
      isBestSeller: true, isActive: true,
      variants: [{ sku: 'RTG-001-OS', stock: 100, attributes: { color: 'Gold' } }],
    },
    {
      name: 'Diya and Agarbatti Gift Set',
      slug: 'diya-agarbatti-gift-set',
      description: 'Set of 2 hand-painted clay diyas with a pack of premium sandalwood agarbatti, presented in a decorative box.',
      shortDescription: 'Hand-painted diyas with sandalwood agarbatti in gift box.',
      productType: 'return-gift', category: returnGiftCat._id,
      collections: [diwaliCol._id, festiveCol._id],
      attributes: { occasion: ['Return Gift', 'Festive'] },
      mrp: 399, salePrice: 279, discountPercentage: disc(399, 279),
      images: [IMG.gift1], tags: ['diya', 'agarbatti', 'diwali', 'return gift'],
      isActive: true,
      variants: [{ sku: 'RTG-002-OS', stock: 150, attributes: { color: 'Beige' } }],
    },
    {
      name: 'Silver Coin Return Gift Set',
      slug: 'silver-coin-return-gift-set',
      description: 'Silver-plated Lakshmi Ganesh coin presented in a velvet pouch and decorative box. Auspicious return gift for religious functions.',
      shortDescription: 'Silver-plated Lakshmi Ganesh coin in velvet pouch and box.',
      productType: 'return-gift', category: returnGiftCat._id,
      collections: [festiveCol._id, weddingCol._id],
      attributes: { metal: ['Original Silver'], occasion: ['Return Gift', 'Wedding'] },
      mrp: 699, salePrice: 499, discountPercentage: disc(699, 499),
      images: [IMG.gift1], tags: ['silver coin', 'return gift', 'religious', 'lakshmi'],
      isBestSeller: true, isActive: true,
      variants: [{ sku: 'RTG-003-OS', stock: 80, attributes: { color: 'White' } }],
    },
    {
      name: 'Brass Pooja Thali Set',
      slug: 'brass-pooja-thali-set',
      description: 'Handcrafted brass pooja thali with small diya, roli pot, and aarti bell, packaged in a ribbon-tied box.',
      shortDescription: 'Handcrafted brass pooja thali with diya, roli and bell.',
      productType: 'return-gift', category: returnGiftCat._id,
      collections: [weddingCol._id, festiveCol._id],
      attributes: { occasion: ['Return Gift', 'Wedding', 'Festive'] },
      mrp: 799, salePrice: 549, discountPercentage: disc(799, 549),
      images: [IMG.gift1], tags: ['brass', 'pooja thali', 'return gift', 'housewarming'],
      isFeatured: true, isActive: true,
      variants: [{ sku: 'RTG-004-OS', stock: 60, attributes: { color: 'Gold' } }],
    },
    {
      name: 'Handmade Soy Candle Gift Box',
      slug: 'handmade-soy-candle-gift-box',
      description: 'Set of 3 handpoured soy wax candles in jasmine, rose, and sandalwood scents in a decorative gift box with ribbon.',
      shortDescription: 'Set of 3 soy candles (jasmine, rose, sandalwood) in gift box.',
      productType: 'return-gift', category: returnGiftCat._id,
      collections: [newArrivalsCol._id],
      attributes: { occasion: ['Return Gift', 'Party'] },
      mrp: 599, salePrice: 399, discountPercentage: disc(599, 399),
      images: [IMG.gift1], tags: ['candle', 'soy', 'return gift', 'fragrance'],
      isNewArrival: true, isTrending: true, isActive: true,
      variants: [{ sku: 'RTG-005-OS', stock: 120, attributes: { color: 'White' } }],
    },

  ]);
  console.log(`Products created: ${products.length}`);

  console.log('\n✅ Seed complete!\n');
  console.log('─'.repeat(50));
  console.log('ADMIN LOGIN:');
  console.log('  admin@styleinneed.com / Admin@123');
  console.log('CUSTOMER LOGIN:');
  console.log('  priya@example.com / Customer@123');
  console.log('─'.repeat(50));
  console.log(`Categories: ${categories.length}`);
  console.log(`Collections: ${collections.length}`);
  console.log(`Products: ${products.length}`);
  console.log(`Size charts: ${sizeChartDocs.length}`);
  console.log('─'.repeat(50));

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
